server:
  port: 9030
  servlet.context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/craftly-intelligence-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  ai:
    openai:
      api-key: sk-proj--PMuDA3uRp6pp3LuX-xvoCC4A
      chat:
        options:
          model: gpt-4
          temperature: 0.0
